INSERT INTO department (id, name)
VALUES(1,Managment),
(2,Production)
(3,Marketing)
INSERT INTO roles (id,title, salary, department_id )
VALUES(1, Manager, Managment)
(2, Engineer, Production)
(3, Marketer, Marketing)
INSERT INTO employee ( id, first_name, last_name, role_id)
VALUES(1, Horatious, Harris,1 )
(2, Johnny, Appleseed, 3)
(3, Zacko, Moondou, 2)